# Generated by Django 4.2.7 on 2023-11-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpLearnApp', '0002_rename_is_staff_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='invalid_login_attempts',
            field=models.CharField(blank=True, default='0', max_length=30, verbose_name='invalid login attempt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='is admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
    ]
