# Generated by Django 4.2.7 on 2023-11-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpLearnApp', '0004_course_discussionforum_role_trainingdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
