# Generated by Django 4.2.7 on 2023-11-20 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corpLearnApp', '0005_announcement_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionforum',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
