# Generated by Django 4.2.7 on 2023-11-20 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corpLearnApp', '0006_discussionforum_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecourse',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
