# Generated by Django 4.2.7 on 2023-11-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpLearnApp', '0007_employeecourse_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecourse',
            name='deadline',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeecourse',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeecourse',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
