# Generated by Django 4.2.7 on 2023-11-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpLearnApp', '0009_alter_employeecourse_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeeconcern',
            name='posted_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
